### ISSUE TITLE
cannot read property oneOf undefined

### ISSUE THREAD

**Issue by Falieson** [jxnblk/gx#5]
Console error points to this line of the code
```
Gx.propTypes = {
  /** Width of column above the breakpoint. Based on a 12 column grid. All numbers in a row should add up to 12 or less. */
  col: _react2.default.PropTypes.oneOf([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12]),
  /** Width in pixels at which columns render side-by-side */
  breakpoint: _react2.default.PropTypes.number
};
```

My code worked before so I'm assuming this is because of upgrading from React 15 to 16 which no longer provides _react2.default.PropTypes (b/c PropTypes is now its own package).

**Comment by raymondsiu** [comment]
Any idea when this might be fixed?
I'm running on React 16 and receiving the same error.

**Comment by Falieson** [comment]
@raymondsiu I'm pretty sure its fixed by the PR. I have published it at `npm i -S @tgrx/gx`
